camunda.bpm.admin-user:
  id: demo
  password: demo
server:
  port: 9099
############# Enable H2 Database browser console #################
##http://localhost:port/h2-console/
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:camunda
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
